#!/usr/bin/env python3
# -*- coding:utf-8 -*-
from page.webpage import WebPage, sleep
from common.readelement import Element
from common.readconfig import ini
import random


vendor = Element('vendor')
element = Element('element')


class PageVendor(WebPage):
    """搜索类"""

    def new_vendor(self):
        """新增供应商"""
        random_number = random.randint(1, 1000)
        self.is_click(vendor['supply_chain_management'])
        self.is_click(vendor['supplier_check_in'])
        self.is_click(vendor['new_vendor'])
        self.input_texts(vendor['input'],"测试供应商全称" + str(random_number),0)
        self.click_drop_n(vendor['input'],0,1)
        self.input_texts(vendor['input'],'供应商简称',2)
        self.click_drop_n(vendor['input'], 0, 3)
        self.is_clicks(vendor['input'],4)
        self.is_clicks(vendor['el_checkbox__inner'],0)
        self.input_texts(vendor['input'],'联系人',5)
        self.input_texts(vendor['input'], '17317795711', 6)
        self.select_address(vendor['input'],7)
        self.input_texts(vendor['input'],'详细测试地址',8)
        self.is_click(vendor['choice'])
        self.is_click(vendor['one'])
        self.input_texts(vendor['input'],'310109199555555555',11)
        self.input_texts(vendor['input'],'13',12)
        self.click_drop_n(vendor['input'], 1, 13)
        self.input_texts(vendor['input'],'上海启明星科技有限公司',14)
        self.input_texts(vendor['input'],'工商银行',15)
        self.input_texts(vendor['input'],'310109199504042222',16)
        self.inset_image(vendor['type_file'],r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\1.jpg',0)
        self.is_click(vendor['other_message'])
        sleep(3)
        self.input_texts(vendor['input'],'紧急联系人',18)
        self.input_texts(vendor['input'], '17317795711', 19)
        self.input_texts(vendor['input'], '主要生产设备', 20)
        self.input_texts(vendor['input'], '主要生产设备', 21)
        self.input_texts(vendor['input'], '主要生产设备', 22)
        self.input_texts(vendor['input'], '主要生产工艺', 23)
        self.input_texts(vendor['input'], '主要试验设备', 24)
        self.input_texts(vendor['input'], '主要试验设备', 25)
        self.input_texts(vendor['input'], '主要试验设备', 26)
        self.input_texts(vendor['input'], '主要检测设备', 27)
        self.input_texts(vendor['input'], '主要检测设备', 28)
        self.input_texts(vendor['input'], '主要检测设备', 29)
        self.input_texts(vendor['input'], '100', 30)
        self.input_texts(vendor['input'], '50', 31)
        self.is_clicks(vendor['el_radio_inner'],4)
        self.is_clicks(vendor['el_radio_inner'], 6)
        self.input_texts(vendor['input'], '10', 32)
        self.input_texts(vendor['input'], '品质管理联系人姓名', 33)
        self.inset_image(vendor['type_file'],r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\2.jpg',1)
        self.inset_image(vendor['type_file'],r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\3.jpg',2)
        self.inset_image(vendor['type_file'],r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\4.jpg',3)
        self.inset_image(vendor['type_file'],r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\5.jpg',4)
        self.inset_image(vendor['type_file'], r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\6.jpg', 5)
        self.inset_image(vendor['type_file'], r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\7.jpg', 6)
        self.is_click(vendor['to_examine'])



    def invite_vendor(self):
        """"邀请供应商"""
        random_number = random.randint(1, 1000)
        self.is_click(vendor['supply_chain_management'])
        self.is_click(vendor['supplier_check_in'])
        self.is_click(vendor['invite_vendor'])
        self.input_texts(vendor['input'],"测试供应商全称" + str(random_number),0)
        self.click_drop_n(vendor['input'],0,1)
        self.input_texts(vendor['input'],'供应商简称',2)
        self.click_drop_n(vendor['input'], 0, 3)
        self.is_clicks(vendor['input'],4)
        self.is_clicks(vendor['el_checkbox__inner'],0)
        self.input_texts(vendor['input'],'联系人',5)
        self.input_texts(vendor['input'], '17317795711', 6)
        self.is_click(vendor['input'])
        self.is_click(vendor['choice'])
        self.is_click(vendor['one'])
        self.input_texts(vendor['input'], '50', 8)
        self.input_drop(vendor['input'],"测试供应商2",9)
        self.input_drop(vendor['input'], "测试公司", 10)
        self.inset_image(vendor['type_file'], r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\1.jpg', 0)
        self.is_click(vendor['save'])
        sleep(1)
        invite_vendor_link = self.element_text(vendor['invite_vendor_link'])
        print("这个是是是是IshmaelIshmaelishi是是hi是i：",invite_vendor_link)
        ini._set('HOST','HOST2',invite_vendor_link)
        self.is_click(vendor['copy_link'])


    def input_invite_vendor(self):
        self.select_address(vendor['input'], 7)
        self.input_texts(vendor['input'],'详细测试地址',8)
        self.input_texts(vendor['input'], '主要生产设备', 9)
        self.input_texts(vendor['input'], '主要生产设备', 10)
        self.input_texts(vendor['input'], '主要生产设备', 11)
        self.input_texts(vendor['input'], '主要生产工艺', 12)
        self.input_texts(vendor['input'], '主要试验设备', 13)
        self.input_texts(vendor['input'], '主要试验设备', 14)
        self.input_texts(vendor['input'], '主要试验设备', 15)
        self.input_texts(vendor['input'], '主要检测设备', 16)
        self.input_texts(vendor['input'], '主要检测设备', 17)
        self.input_texts(vendor['input'], '主要检测设备', 18)
        self.input_texts(vendor['input'], '100', 19)
        self.input_texts(vendor['input'], '50', 20)
        self.is_clicks(vendor['el_radio_inner'], 0)
        self.is_clicks(vendor['el_radio_inner'], 2)
        self.input_texts(vendor['input'], '10', 21)
        self.input_texts(vendor['input'], '品质管理联系人姓名', 22)
        self.is_click(vendor['choice'])
        self.is_click(vendor['one'])
        self.input_texts(vendor['input'], '20', 24)
        self.input_texts(vendor['input'], '310109199505054444', 25)
        self.input_texts(vendor['input'], '13', 26)
        self.click_drop_n(vendor['input'], 1, 27)
        self.input_texts(vendor['input'], '上海启明星科技有限公司', 28)
        self.input_texts(vendor['input'], '工商银行', 29)
        self.input_texts(vendor['input'], '310109199504042222', 30)
        self.input_texts(vendor['input'], '详细注册地址', 31)
        self.inset_image(vendor['type_file'], r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\1.jpg', 0)
        self.inset_image(vendor['type_file'],r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\2.jpg',1)
        self.inset_image(vendor['type_file'],r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\3.jpg',2)
        self.inset_image(vendor['type_file'],r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\4.jpg',3)
        self.inset_image(vendor['type_file'],r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\5.jpg',4)
        self.inset_image(vendor['type_file'], r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\6.jpg', 5)
        self.inset_image(vendor['type_file'], r'C:\Users\admin\Desktop\daima\pytest_handopen_ui\images\7.jpg', 6)
        self.is_click(vendor['to_examine'])


    def design_order(self):
        self.is_click(vendor['supply_chain_management'])
        self.is_click(element['design_order'])
        self.is_click(element['new_design_order'])
        self.input_drop(element['choice_pic'],'供应链',0)
        self.is_clicks(element['el_checkbox__inner'],0)
        self.is_clicks(element['el_checkbox__inner'],7)
        self.is_clicks(element['el_checkbox__inner'], 8)
        self.input_texts(element['contentInput'],'15',0)
        self.input_texts(element['contentInput'], '20', 1)
        self.input_texts(element['input_comment'],'备注信息哈哈哈哈',0)
        self.inset_image(element['type_file'],r'C:\Users\admin\Desktop\Rick_blunt\rickblunt\pytest_handopen_ui\images\1.jpg', 0)
        self.is_clicks(element['confirm'],1)