
# ————————————————————————————————————通用元素
# 输入框
input: 'css==[class="el-input__inner"]'
# 方形按钮
el_checkbox__inner: 'css==[class="el-checkbox__inner"]'
# 北京市
beijing: 'xpath==//span[text()="北京市"]'
# 市辖区
shixiaqu: 'xpath==//span[text()="市辖区"]'
# 东城区
dongchengqu: 'xpath==//span[text()="东城区"]'
# 东华门街道
donghuamenjiedao: 'xpath==//span[text()="东华门街道"]'
# 插入图片
type_file: 'css==[type="file"]'
# 园钮
el_radio_inner: 'css==[class="el-radio__inner"]'
# 提交审核
to_examine: 'xpath==//span[text()="提交审核"]'
# 今天
today: 'css==[class="available today"]'
# 确认
confirm: 'xpath==//span[text()="确认"]'
# 审批确认
if_confirm: 'css==[class="el-button el-button--default el-button--small el-button--primary "]'
# 确定
确定: 'css==[class="el-button el-button--default el-button--small el-button--primary "]'
# search
search: 'xpath==//span[text()="搜索"]'
# 商品名称
product_name: 'xpath==//span[text()="商品名称"]'
# 下拉
down_button: 'css==[class="el-input__suffix-inner"]'
# 备注
remake: 'css==[class="el-textarea__inner"]'
# 人事管理
hr_management: 'xpath==//span[text()="人事管理"]'
# 我的工作台
function_not_open: 'css==[class="red-text m-t-20 m-l-20"]'
# 请输入商品内容
input_product: 'css==[placeholder="请输入搜索内容"]'
# 请输入商品名称
input_goods: 'css==[placeholder="请输入商品名称"]'
# 请输入规格名称
input_sku: 'css==[placeholder="请输入规格名称"]'
# 请输入生产成本
productionCostInput: 'css==[placeholder="请输入生产成本"]'
# 请输入包装成本
packagingCostInput: 'css==[placeholder="请输入包装成本"]'
# 请输入运费成本
shippingCostInput: 'css==[placeholder="请输入运费成本"]'
# 付款
pay: 'xpath==//span[text()="付款"]'
# 我的项目
my_project: 'xpath==//a[contains(div/text(), "我的项目")]'
# 创建供应商链接
found_vendor_link: 'xpath==//span[text()="创建供应商链接"]'
# 确认创建
confirm_creation: 'xpath==//span[text()="确认创建"]'
# 请输入内容
contentInput: 'css==[placeholder="请输入内容"]'
# 补充收货信息
receivingInfoInput: 'xpath==//span[text()="补充收货信息"]'
# 收货人
receiverName: 'css==[placeholder="请输入收货人"]'
# 收货人手机号
receiverPhoneNumber: 'css==[placeholder="请输入收货人手机号"]'
# [placeholder="请选择省份/城市/地区/街道"]
input_town: 'css==[placeholder="请选择省份/城市/地区/街道"]'
# 详细地址
shippingAddress: 'css==[placeholder="请输入详细地址"]'
# 修改
put: 'xpath==//span[text()="修改"]'
# 项目
project: 'css==[class="el-link--inner"]'
# 修改收货信息
put_address: 'xpath==//span[text()="修改收货信息"]'
# 请选择
selct_please: 'css==[placeholder="请选择"]'


# __________________________________________页面元素
# 项目管理
order_project: 'xpath==//span[text()="项目管理"]'
# 订单审核
order_exm: 'xpath==//div[contains(text(),"订单审核")]'
# 新项目立项
new_project: 'xpath==//div[contains(text(),"新项目立项")]'
# 下单生产
place_order: 'xpath==//div[contains(text(),"下单生产")]'
# 项目编号
project_number: 'xpath==//h2[@data-v-7806f16a]'
# 点击复制项目编码
copy_project_no: 'xpath==//span[text()="点击复制项目编码"]'
# 创建订单
new_order: 'xpath==//span[text()="创建订单"]'
# 选择商品
select_goods: 'xpath==//span[text()="选择商品"]'
# 供应链管理
supply_chain: 'xpath==//span[text()="供应链管理"]'
# 自定义商品
customs_goods: 'xpath==//span[text()="自定义商品"]'
# 去审核
go_order_exm: 'xpath==//span[text()="去审核"]'
# 确认销售价
confirm_sales: 'xpath==//span[text()="确认销售价"]'
# 请输入供应商名称/编码
placeholder: 'css==[placeholder="请输入供应商名称/编码"]'
# 商品管理
product_management: 'xpath==//span[text()="商品管理"]'
# 待审核产品
pending_products: 'xpath==//div[contains(text(),"待审核产品")]'
# 关联
linkage: 'xpath==//span[text()="关联"]'
# 关联为此产品
assocProd: 'xpath==//span[text()="关联为此产品"]'
# 财务管理
finMgmt: 'xpath==//span[text()="财务管理"]'
# 付款审批
payApproval: 'xpath==//div[contains(text(),"付款审批")]'
# 通过
pass: 'xpath==//span[text()="通过"]'
# 其他
others: 'xpath==//span[text()="其他"]'
# 付款单
payDoc: 'css==a[href="/admin/finance/bill_payable"] > div[data-v-2df612f0]'
# 付款账户
payAccount: 'css==[placeholder="付款账户"]'
# 请输入生产成本
input_productionCost: 'css==[placeholder="请输入生产成本"]'
# 请输入包装成本
input_packagingCost: 'css==[placeholder="请输入包装成本"]'
# 请输入运费成本
input_shippingCost: 'css==[placeholder="请输入运费成本"]'
# link
link: 'css==[class="el-dialog__body"]'
# 商品名称
sp_name: 'xpath==//span[text()="商品名称"]'
# 选择项目、项目编码
select2: 'xpath==//span[text()="项目/项目编码"]'
# 复制链接
copy_link: 'xpath==//span[text()="复制链接"]'

# //span[text()="项目/项目编码"]
项目编码: 'xpath==//span[text()="项目/项目编码"]'
